chore: Angular 18 support
ui-router/angular pull request #993
Opened 2024-07-05 12:17 UTC by lukaVarga

2024-07-09 15:53 UTC, sbschorer requested changes
Thanks for opening this PR :)

2024-07-09 15:53 UTC, sbschorer commented on test-angular-versions/v18/src/app/app.config.ts
> +}
This seems to be duplicated from `app.module.ts`

2024-07-09 15:53 UTC, sbschorer commented on downstream_projects.json
> +    "sample-app-angular": "https://github.com/lukaVarga/ui-router-sample-app-angular.git",
I guess, this should be changed back to
```suggestion
    "sample-app-angular": "https://github.com/ui-router/sample-app-angular.git",
```

2024-07-10 06:53 UTC, lukaVarga commented
Thanks for the review. Adjusted :)

2024-07-10 09:45 UTC, merged